### ISSUE TITLE
Using layerFilterSubsetString for a layer in a group problem

### ISSUE THREAD

**Issue by tudorbarascu** [elpaso/qgis3-server-vagrant#9]
Testing the Access Control Server Plugin ( https://github.com/elpaso/qgis3-server-vagrant/edit/master/resources/web/plugins/accesscontrol/accesscontrol.py ) and I noticed the following:

While testing the SQL filter (``layerFilterSubsetString``) on the "restricted" layer I noticed it works well if you add just that WMS layer. 

But if you have a group that contains the "restricted" layer, then the filtering is bypassed and the Group shows all the data (although only some of the data in the "restricted" layer should be shown)

**Comment by elpaso** [comment]
I suspect it's an upstream issue in QGIS.

**Comment by tudorbarascu** [comment]
Well.. you fixed that :) .. but I forgot to closed the issue here. Thanks again.
